""" Desafio 009: """

n = int(input('Digite um número: '))
print('-'*25)
print(f'	TABUADA DE {n}')
print('-'*25)
print('		Multiplicação: ')
print(f'{n} x 1  = {n*1}')
print(f'{n} x 2  = {n*2}')
print(f'{n} x 3  = {n*3}')
print(f'{n} x 4  = {n*4}')
print(f'{n} x 5  = {n*5}')
print(f'{n} x 6  = {n*6}')
print(f'{n} x 7  = {n*7}')
print(f'{n} x 8  = {n*8}')
print(f'{n} x 9  = {n*9}')
print(f'{n} x 10 = {n*10}')
print('-'*25)
print('		Adição: ')
print(f'{n} + 1  = {n + 1}')
print(f'{n} + 2  = {n + 2}')
print(f'{n} + 3  = {n + 3}')
print(f'{n} + 4  = {n + 4}')
print(f'{n} + 5  = {n + 5}')
print(f'{n} + 6  = {n + 6}')
print(f'{n} + 7  = {n + 7}')
print(f'{n} + 8  = {n + 8}')
print(f'{n} + 9  = {n + 9}')
print(f'{n} + 10 = {n + 10}')
print('-'*25)
